# Use Python 3.9 as base image
FROM python:3.9

# set working directory
WORKDIR /app

# install selenium
RUN pip install selenium==2.48.0

# copy files
COPY ecnu_net.py .
COPY phantomjs .

# run script
CMD python -u ecnu_net.py -u $USERNAME -p $PASSWORD -m $METHOD --url $URL --force
